dependencies:
  - python=3.9
  - pip
  - pip:
    - ..  # d2l
    - mxnet-cu102==1.7.0
    - torch==1.12.0+cu102
    - -f https://download.pytorch.org/whl/torch_stable.html
    - torchvision==0.13.0+cu102
    - -f https://download.pytorch.org/whl/torch_stable.html
    - tensorflow==2.11.0
    - tensorflow-probability==0.18.0
    - tensorflow-datasets==4.7.0
    - jaxlib==0.4.1+cuda11.cudnn82
    - "jax[cuda11_cudnn82]==0.4.1"
    - -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
    - flax
    - syne-tune[gpsearchers]==0.3.2
